apiVersion: stackgres.io/v1
kind: SGInstanceProfile
metadata:
  name: {{ include "stackgres.profileName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackgres.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  cpu: {{ .Values.resources.cpu | quote }}
  memory: {{ .Values.resources.memory | quote }}
